version: "3.8"
services:
  web:
    build: .
    command: bundle exec rackup --host 0.0.0.0 -p 4567
    ports:
      - "4567:4567"
    volumes:
      - .:/frank_calendar_docker
    environment:
      TZ: America/Sao_Paulo

  db:
    image: postgres:13
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
